/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AberturaGratuitaRouteImport } from './routes/abertura-gratuita'
import { Route as AdvogadosRouteImport } from './routes/advogados'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as ServicosRouteImport } from './routes/servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AberturaGratuitaRoute = AberturaGratuitaRouteImport.update({
  id: '/abertura-gratuita',
  path: '/abertura-gratuita',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadosRoute = AdvogadosRouteImport.update({
  id: '/advogados',
  path: '/advogados',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abertura-gratuita': typeof AberturaGratuitaRoute
  '/advogados': typeof AdvogadosRoute
  '/planos': typeof PlanosRoute
  '/saude': typeof SaudeRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abertura-gratuita': typeof AberturaGratuitaRoute
  '/advogados': typeof AdvogadosRoute
  '/planos': typeof PlanosRoute
  '/saude': typeof SaudeRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abertura-gratuita': typeof AberturaGratuitaRoute
  '/advogados': typeof AdvogadosRoute
  '/planos': typeof PlanosRoute
  '/saude': typeof SaudeRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abertura-gratuita'
    | '/advogados'
    | '/planos'
    | '/saude'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abertura-gratuita'
    | '/advogados'
    | '/planos'
    | '/saude'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/abertura-gratuita'
    | '/advogados'
    | '/planos'
    | '/saude'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AberturaGratuitaRoute: typeof AberturaGratuitaRoute
  AdvogadosRoute: typeof AdvogadosRoute
  PlanosRoute: typeof PlanosRoute
  SaudeRoute: typeof SaudeRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abertura-gratuita': {
      id: '/abertura-gratuita'
      path: '/abertura-gratuita'
      fullPath: '/abertura-gratuita'
      preLoaderRoute: typeof AberturaGratuitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogados': {
      id: '/advogados'
      path: '/advogados'
      fullPath: '/advogados'
      preLoaderRoute: typeof AdvogadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AberturaGratuitaRoute: AberturaGratuitaRoute,
  AdvogadosRoute: AdvogadosRoute,
  PlanosRoute: PlanosRoute,
  SaudeRoute: SaudeRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
